In [4]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn import linear_model

df = pd.read_csv('final_data.csv')
#TODO: replace with mean of year instead of mean of all time
df.replace(['-', '(X)'], float("nan"), inplace=True)
df = df.apply(pd.to_numeric)
for col in df.columns:
    df[col].replace(float("nan"), df[col].mean(), inplace=True)
df = MinMaxScaler(feature_range=(-1, 1)).fit_transform(df)
# print(df[(df == '-').any(axis=1)])
years = df[:, 0]
longitudes = df[:, 2]
latitudes = df[:, 3]
X = np.vstack((years, longitudes, latitudes)).T
print(X)

[[-1.          0.25595238  0.09381663]
 [-1.          0.73214286 -0.31769723]
 [-1.          0.62103175 -0.20255864]
 ...
 [ 1.         -0.16865079  0.32835821]
 [ 1.         -0.20238095  0.445629  ]
 [ 1.         -0.21230159  1.        ]]


In [5]:
inc_model_ols = linear_model.LinearRegression(normalize=True)
incs = df[:, 4]
inc_model_ols.fit(X, incs)
print(inc_model_ols.coef_)
print(inc_model_ols.intercept_)

[ 0.06980302 -0.38360147 -0.32875502]
-0.5840963894665046


c:\Users\ishaa\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(


In [6]:
age_model_ols = linear_model.LinearRegression(normalize=True)
ages = df[:, 5]
age_model_ols.fit(X, ages)
print(age_model_ols.coef_)
print(age_model_ols.intercept_)

[ 0.24488483 -0.12979739 -0.19119114]
-0.8950502522461439


c:\Users\ishaa\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(


In [7]:
pop_model_ols = linear_model.LinearRegression(normalize=True)
pops = df[:, 6]
pop_model_ols.fit(X, pops)
print(pop_model_ols.coef_)
print(pop_model_ols.intercept_)

[ 0.01263346 -0.33613542 -0.53810437]
-0.7486845974350531


c:\Users\ishaa\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(


In [8]:
room_model_ols = linear_model.LinearRegression(normalize=True)
rooms = df[:, 8]
room_model_ols.fit(X, rooms)
print(room_model_ols.coef_)
print(room_model_ols.intercept_)

[ 0.08515903 -0.65639852 -0.55647159]
-0.7353156604599288


c:\Users\ishaa\anaconda3\lib\site-packages\sklearn\linear_model\_base.py:141: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  warnings.warn(


In [12]:
from sklearn.model_selection import train_test_split
training_set, test_set = train_test_split(df, test_size=0.2, random_state=42)
print(training_set)
print(test_set)


[[-0.11111111 -0.14991304  0.31547619 ... -0.96414339 -0.95528263
  -0.55778894]
 [ 0.55555556  0.02817391 -0.25       ... -0.62623128 -0.79247363
  -0.44944724]
 [-0.55555556 -0.00707246  0.00793651 ... -0.31440651 -0.99833097
  -0.83467337]
 ...
 [-0.33333333 -0.71455072  0.21626984 ... -0.21565241 -0.99855141
  -0.5758794 ]
 [-1.          0.07014493 -0.08928571 ... -0.87918859 -0.99836246
  -0.76311558]
 [ 0.77777778  0.61692754 -0.30357143 ... -0.99316332 -0.98425445
  -0.54894977]]
[[ 1.          0.61368116 -0.47420635 ... -0.65615077 -0.77263423
  -0.73919598]
 [-0.33333333 -0.30017391  0.39880952 ... -0.13039176 -0.99804755
  -0.58040201]
 [-0.33333333 -0.1053913   0.26984127 ... -0.50788468 -0.99864588
  -0.65788945]
 ...
 [ 0.11111111 -0.11976812  0.26785714 ... -0.27502361 -0.84254448
  -0.55276382]
 [-0.11111111  0.63547826 -0.47420635 ... -0.99641974 -1.
  -0.80693467]
 [-0.11111111  0.51072464 -0.91865079 ... -0.96860523 -0.99401669
  -0.71517588]]
